{
  "swagger": "2.0",
  "info": {
    "title": "API Dokumentáció",
    "description": "Az API leírása.",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/login/": {
      "post": {
        "description": "Bejelentkezés útja",
        "tags":["Authorization"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string",
                  "example": "papp.lajos42"
                },
                "password": {
                  "type": "string",
                  "example": "Jelszó123"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/login/changePassword": {
      "post": {
        "description": "Jelszó megváltoztatása az előző jelszó használatával",
        "tags":["Authorization"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentpassword": {
                  "type": "string",
                  "example": "Jelszó123"
                },
                "currentpasswordagain": {
                  "type": "string",
                  "example": "Jelszó123"
                },
                "username": {
                  "type": "string",
                  "example": "papp.lajos42"
                },
                "newpassword": {
                  "type": "string",
                  "example": "Újjelszó123"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/uzenet/": {
      "get": {
        "description": "Üzenetek lekérése user ID alapján",
        "tags": ["Üzenetek"],
        "responses": {
          "201": {
            "description": "Lekérve",
            "schema": {
              "type": "object",
              "properties": {
                "elkuldott": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "Message": {
                        "type": "object",
                        "properties": {
                          "dataValues": {
                            "type": "object",
                            "properties": {
                              "ID": {
                                "type": "integer",
                                "example": 1
                              },
                              "senderUserID": {
                                "type": "integer",
                                "example": 3
                              },
                              "message": {
                                "type": "string",
                                "example": "Példa üzenet"
                              },
                              "date": {
                                "type": "string",
                                "format": "date-time",
                                "example": "2025-03-24T16:54:41.000Z"
                              },
                              "receivers": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "User": {
                                      "type": "object",
                                      "properties": {
                                        "dataValues": {
                                          "type": "object",
                                          "properties": {
                                            "ID": {
                                              "type": "integer",
                                              "example": 1
                                            },
                                            "username": {
                                              "type": "string",
                                              "example": "laci"
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              "sender": {
                                "type": "object",
                                "properties": {
                                  "User": {
                                    "type": "object",
                                    "properties": {
                                      "dataValues": {
                                        "type": "object",
                                        "properties": {
                                          "ID": {
                                            "type": "integer",
                                            "example": 3
                                          },
                                          "username": {
                                            "type": "string",
                                            "example": "lajos"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "example": [
                    {
                      "Message": {
                        "dataValues": {
                          "ID": 1,
                          "senderUserID": 3,
                          "message": "Példa üzenet",
                          "date": "2025-03-24T16:54:41.000Z",
                          "receivers": [
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 1,
                                  "username": "laci"
                                }
                              }
                            },
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 2,
                                  "username": "rebeka"
                                }
                              }
                            }
                          ],
                          "sender": {
                            "User": {
                              "dataValues": {
                                "ID": 3,
                                "username": "lajos"
                              }
                            }
                          }
                        }
                      }
                    },
                    {
                      "Message": {
                        "dataValues": {
                          "ID": 1,
                          "senderUserID": 3,
                          "message": "Példa üzenet2",
                          "date": "2025-03-26T16:54:41.000Z",
                          "receivers": [
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 1,
                                  "username": "laci"
                                }
                              }
                            },
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 2,
                                  "username": "rebeka"
                                }
                              }
                            }
                          ],
                          "sender": {
                            "User": {
                              "dataValues": {
                                "ID": 3,
                                "username": "lajos"
                              }
                            }
                          }
                        }
                      }
                    }
                  ]
                },
                "kapott": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "Message": {
                        "type": "object",
                        "properties": {
                          "dataValues": {
                            "type": "object",
                            "properties": {
                              "ID": {
                                "type": "integer",
                                "example": 1
                              },
                              "senderUserID": {
                                "type": "integer",
                                "example": 1
                              },
                              "message": {
                                "type": "string",
                                "example": "Példa üzenet 3"
                              },
                              "date": {
                                "type": "string",
                                "format": "date-time",
                                "example": "2025-03-24T16:54:41.000Z"
                              },
                              "receivers": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "User": {
                                      "type": "object",
                                      "properties": {
                                        "dataValues": {
                                          "type": "object",
                                          "properties": {
                                            "ID": {
                                              "type": "integer",
                                              "example": 3
                                            },
                                            "username": {
                                              "type": "string",
                                              "example": "lajos"
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              "sender": {
                                "type": "object",
                                "properties": {
                                  "User": {
                                    "type": "object",
                                    "properties": {
                                      "dataValues": {
                                        "type": "object",
                                        "properties": {
                                          "ID": {
                                            "type": "integer",
                                            "example": 1
                                          },
                                          "username": {
                                            "type": "string",
                                            "example": "laci"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "example": [
                    {
                      "Message": {
                        "dataValues": {
                          "ID": 1,
                          "senderUserID": 1,
                          "message": "Példa üzenet 3",
                          "date": "2025-03-24T16:54:41.000Z",
                          "receivers": [
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 3,
                                  "username": "lajos"
                                }
                              }
                            },
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 2,
                                  "username": "rebeka"
                                }
                              }
                            }
                          ],
                          "sender": {
                            "User": {
                              "dataValues": {
                                "ID": 1,
                                "username": "laci"
                              }
                            }
                          }
                        }
                      }
                    },
                    {
                      "Message": {
                        "dataValues": {
                          "ID": 1,
                          "senderUserID": 1,
                          "message": "Példa üzenet 4",
                          "date": "2025-03-26T16:54:41.000Z",
                          "receivers": [
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 3,
                                  "username": "lajos"
                                }
                              }
                            },
                            {
                              "User": {
                                "dataValues": {
                                  "ID": 2,
                                  "username": "rebeka"
                                }
                              }
                            }
                          ],
                          "sender": {
                            "User": {
                              "dataValues": {
                                "ID": 1,
                                "username": "laci"
                              }
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "post": {
        "description": "Új üzenet küldése",
        "tags": ["Üzenetek"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "description": "Az üzenet szövege",
                  "example": "Mi a hézag hapsikám?"
                },
                "date": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2025-03-24T16:54:41.000Z"
                },
                "receiverlist": {
                  "type": "array",
                  "description": "egyes felhasználók akik nem tartoznak egy csoportokhoz",
                  "example": [
                    {
                      "ID": 4,
                      "username": "jozsi",
                      "role": "szulo"
                    },
                    {
                      "ID": 5,
                      "username": "patrik",
                      "role": "admin"
                    }
                  ]
                },
                "receiverGrouplist": {
                  "type": "array",
                  "description": "egy tömbb amiben a csoportok vannak benne amiknek az üzentet küldik el",
                  "example": [
                    {
                      "ID": 1,
                      "name": "1.b",
                      "studentList": [1, 2]
                    }
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "example": {
                "ID": 10,
                "senderUserID": 1,
                "message": "Mi a hézag hapsikám?",
                "date": "2025-03-24T16:54:41.000Z"
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },

    "/uzenet/uzenetekreceivers": {
      "get": {
        "description": "Egy tömbb amiben szerepel minden felhasználó, illetve csoport a benne lévő diákok ID-jaival együtt",
        "tags": ["Üzenetek"],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "properties": {
                "singleUsers": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "User": {
                        "type": "object",
                        "properties": {
                          "dataValues": {
                            "type": "object",
                            "properties": {
                              "ID": {
                                "type": "integer",
                                "example": 1
                              },
                              "username": {
                                "type": "string",
                                "example": "laci"
                              },
                              "role": {
                                "type": "string",
                                "example": "diak"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "example": [
                    {
                      "User": {
                        "dataValues": {
                          "ID": 1,
                          "username": "laci",
                          "role": "diak"
                        }
                      }
                    },
                    {
                      "User": {
                        "dataValues": {
                          "ID": 2,
                          "username": "rebeka",
                          "role": "diak"
                        }
                      }
                    }
                  ]
                },
                "groups": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "ID": {
                        "type": "integer",
                        "example": 1
                      },
                      "name": {
                        "type": "string",
                        "example": "1.b"
                      },
                      "studentList": {
                        "type": "array",
                        "items": {
                          "type": "integer"
                        },
                        "example": [1, 2]
                      }
                    }
                  },
                  "example": [
                    {
                      "ID": 1,
                      "name": "1.b",
                      "studentList": [1, 2]
                    }
                  ]
                }
              },
              "example": {
                "singleUsers": [
                  {
                    "User": {
                      "dataValues": {
                        "ID": 1,
                        "username": "laci",
                        "role": "diak"
                      }
                    }
                  },
                  {
                    "User": {
                      "dataValues": {
                        "ID": 2,
                        "username": "rebeka",
                        "role": "diak"
                      }
                    }
                  }
                ],
                "groups": [
                  {
                    "ID": 1,
                    "name": "1.b",
                    "studentList": [1, 2]
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },

    "/orarend/": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "weekStart",
            "in": "query",
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/orarend/getTeachers": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/orarend/getLessons": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/hianyzas/": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "post": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/hianyzas/{id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/hianyzas/getStudentsInGroup/{groupID}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "groupID",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/hianyzas/postAbsence": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "studentID": {
                  "example": "any"
                },
                "teacherID": {
                  "example": "any"
                },
                "lessonID": {
                  "example": "any"
                },
                "date": {
                  "example": "any"
                },
                "excused": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/hazikGroups": {
      "get": {
        "tags": ["Házifeladatok tanár"],
        "description": "Lekéri az összes csoportot amiknek a tanár típusú felhasználók házifeladatot tud feladni",
        "responses": {
          "201": {
            "description": "Sikeres lekérés",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "ID": {
                    "type": "integer",
                    "example": 1
                  },
                  "name": {
                    "type": "string",
                    "example": "1.b"
                  },
                  "studentList": {
                    "type": "array",
                    "items": {
                      "type": "integer"
                    },
                    "example": [1, 2]
                  }
                }
              },
              "example": [
                {
                  "ID": 1,
                  "name": "1.b",
                  "studentList": [1, 2]
                },
                {
                  "ID": 2,
                  "name": "1.a",
                  "studentList": [3, 4]
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },

    "/feladat/haziktanar": {
      "get": {
        "tags": ["Házifeladatok tanár"],
        "description": "Lekéri az összes feladatot amit az adott felhasználó küldött ki",
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "feladat": {
                    "type": "object",
                    "properties": {
                      "Assignment": {
                        "type": "object",
                        "properties": {
                          "dataValues": {
                            "type": "object",
                            "properties": {
                              "ID": {
                                "type": "integer",
                                "example": 1
                              },
                              "senderUserID": {
                                "type": "integer",
                                "example": 3
                              },
                              "desc": {
                                "type": "string",
                                "example": "Oldd meg x és y feladatot"
                              },
                              "deadline": {
                                "type": "string",
                                "format": "date-time",
                                "example": "2025-03-29T16:55:00.000Z"
                              },
                              "uploadDate": {
                                "type": "string",
                                "format": "date-time",
                                "example": "2025-03-24T13:54:41.000Z"
                              },
                              "senderUserName": {
                                "type": "string",
                                "example": "lajos"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "anwsers": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "CompletedAssignment": {
                          "type": "object",
                          "properties": {
                            "dataValues": {
                              "type": "object",
                              "properties": {
                                "ID": {
                                  "type": "integer",
                                  "example": 1
                                },
                                "assignmentID": {
                                  "type": "integer",
                                  "example": 1
                                },
                                "studentID": {
                                  "type": "integer",
                                  "example": 1
                                },
                                "date": {
                                  "type": "string",
                                  "format": "date-time",
                                  "example": "2025-03-25T09:15:34.000Z"
                                },
                                "textAnswer": {
                                  "type": "string",
                                  "example": "Kész van minden"
                                },
                                "status": {
                                  "type": "string",
                                  "example": "Leadva"
                                },
                                "senderUserName": {
                                  "type": "string",
                                  "example": "laci"
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "example": [
                      {
                        "CompletedAssignment": {
                          "dataValues": {
                            "ID": 1,
                            "assignmentID": 1,
                            "studentID": 1,
                            "date": "2025-03-25T09:15:34.000Z",
                            "textAnswer": "Kész van minden",
                            "status": "Leadva",
                            "senderUserName": "laci"
                          }
                        }
                      },
                      {
                        "CompletedAssignment": {
                          "dataValues": {
                            "ID": 2,
                            "assignmentID": 1,
                            "studentID": 2,
                            "date": "2025-03-24T13:54:41.000Z",
                            "textAnswer": "",
                            "status": "Nincs leadva",
                            "senderUserName": "rebeka"
                          }
                        }
                      }
                    ]
                  }
                }
              },
              "example": [
                {
                  "feladat": {
                    "Assignment": {
                      "dataValues": {
                        "ID": 1,
                        "senderUserID": 3,
                        "desc": "Oldd meg x és y feladatot",
                        "deadline": "2025-03-29T16:55:00.000Z",
                        "uploadDate": "2025-03-24T13:54:41.000Z",
                        "senderUserName": "lajos"
                      }
                    }
                  },
                  "anwsers": [
                    {
                      "CompletedAssignment": {
                        "dataValues": {
                          "ID": 1,
                          "assignmentID": 1,
                          "studentID": 1,
                          "date": "2025-03-25T09:15:34.000Z",
                          "textAnswer": "Kész van minden",
                          "status": "Leadva",
                          "senderUserName": "laci"
                        }
                      }
                    },
                    {
                      "CompletedAssignment": {
                        "dataValues": {
                          "ID": 2,
                          "assignmentID": 1,
                          "studentID": 2,
                          "date": "2025-03-24T13:54:41.000Z",
                          "textAnswer": "",
                          "status": "Nincs leadva",
                          "senderUserName": "rebeka"
                        }
                      }
                    }
                  ]
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },


    "/feladat/hazikdiak": {
      "get": {
        "tags":["Házifeladatok diák"],
        "description": "Lekéri az éppen bejelentkezve lévő diák típusú felhasználónak kiosztott feladatokat",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/newassignment": {
      "post": {
        "description": "Új feladat feltöltése",
        "tags": ["Házifeladatok tanár"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Groups": {
                  "type": "array",
                  "description": "Az osztály akinek ki lett osztva (azért tömb hogyha meggondoljuk magunkat, hogy több osztálynak is lehessen házit küldeni, ne legyen annyi dolgunk)",
                  "example": [
                    {
                      "ID": 1,
                      "name": "1.b",
                      "studentList": [1, 2]
                    }
                  ]
                },
                "Description": {
                  "type": "string",
                  "description": "A feladat leírása",
                  "example": "Oldd meg yz feladatot."
                },
                "DeadLine": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Határidő idő amit frontendről kapunk",
                  "example": "2025-03-30T01:17:00.000Z"
                },
                "UploadDate": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Feltöltési idő amit frontendről kapunk",
                  "example": "2025-03-27T13:30:38.234Z"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Assignment created",
            "schema": {
              "type": "object",
              "properties": {
                "Assignment": {
                  "type": "object",
                  "properties": {
                    "dataValues": {
                      "type": "object",
                      "properties": {
                        "ID": {
                          "type": "integer",
                          "example": 1
                        },
                        "teacherID": {
                          "type": "integer",
                          "example": 1
                        },
                        "desc": {
                          "type": "string",
                          "example": "Oldd meg yz feladatot."
                        },
                        "deadline": {
                          "type": "string",
                          "format": "date-time",
                          "example": "2025-03-30T01:17:00.000Z"
                        },
                        "uploadDate": {
                          "type": "string",
                          "format": "date-time",
                          "example": "2025-03-27T13:30:38.234Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },

    "/feladat/hazikdiak/{id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Sikeres lekérés"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/modifycompletedassignment": {
      "patch": {
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ID": {
                  "example": "any"
                },
                "assignmentID": {
                  "example": "any"
                },
                "date": {
                  "example": "any"
                },
                "status": {
                  "example": "any"
                },
                "studentID": {
                  "example": "any"
                },
                "textAnswer": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/getAssignmentFiles/": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "assignmentid",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/getCompletedAssignmentFiles/": {
      "post": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/deleteAssignment/{assignmentId}": {
      "delete": {
        "description": "",
        "parameters": [
          {
            "name": "assignmentId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/deleteAnswerFile/{fileId}": {
      "delete": {
        "description": "",
        "parameters": [
          {
            "name": "fileId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/feladat/uploadassignmentfiles": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "assignmentId": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/feladat/uploadcompletedassignmentfiles": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "completedAssignmentId": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/jegy/": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "studentID": {
                  "example": "any"
                },
                "Value": {
                  "example": "any"
                },
                "Multiplier": {
                  "example": "any"
                },
                "subjectName": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/jegy/csoportjegy": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/admin/register/{token}": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ID": {
                  "example": "any"
                },
                "name": {
                  "example": "any"
                },
                "password": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/admin/addTeacherUsers": {
      "post": {
        "description": "",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "length": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/admin/getAllGroupsWithStudents": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/admin/deleteMessage/{ID}": {
      "delete": {
        "description": "",
        "parameters": [
          {
            "name": "ID",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/csoport/tanarcsoport": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/csoport/csoporttag": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/szulo/orarend/{id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/szulo/jegy/{id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/szulo/hianyzas/{id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/tanar/tantargy": {
      "get": {
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}